version: '3.8'

services:
  db:
    env_file:
      - .env
    container_name: simple_shop_systeme_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_shop_dev
    ports:
      - 15432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data:rw

  php-fpm:
    env_file:
      - .env
    container_name: simple_shop_systeme_php-fpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/var/www

  nginx:
    env_file:
      - .env
    container_name: simple_shop_systeme_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgresql: